import "./globals.css";
import type { Metadata } from "next";

import Header from "../components/Header";
import Footer from "@/components/Footer";
import Section1 from "@/components/Section1";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body data-class={""}>
        <header>
          <Header />
        </header>

        <main>{children}</main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
